---
# list of applications to install
general:
  local_home: "{{ lookup('env','HOME') }}"

# homebrew applications
applications:
  - docker-compose
  - dotnet
  - git
  - gitmoji
  - graphviz
  - nvm
  - nuget
  - openconnect
  - ssh-copy-id
  - vim
  - yarn
  - zsh

# homebrew cask applications
cask_applications:
  - android-file-transfer
  - anki
  - dbeaver-community
  - franz
  - github
  - gitkraken
  - google-chrome
  - intellij-idea-ce
  - iterm2
  - keka
  - libreoffice
  - ngrok
  - pritunl
  - postman
  - spotify
  - slack
  - sourcetree
  - visual-studio-code
  - vlc
  - zoom

# manual download applications
downloads:
  docker:
    name: Docker Mac with intel chip
    url: https://desktop.docker.com/mac/main/amd64/Docker.dmg?utm_source=docker&utm_medium=webreferral&utm_campaign=docs-driven-download-mac-amd64
    dest: "{{general.local_home}}/Downloads/"
  visualstudio:
    name: Visual Studio Professional 2022 Preview
    url: https://aka.ms/vs/mac/2022-preview
    dest: "{{general.local_home}}/Downloads/"

#sdkman
sdkman_script_install_url: http://get.sdkman.io
sdkman_folder: '{{general.local_home}}/.sdkman'
gradle_version: 3.5
java_version: 11.0.11.hs-adpt
maven_version: 3.5.0