---
# list of applications to install
general:
  local_home: "{{ lookup('env','HOME') }}"

# homebrew applications
applications:
  - docker-compose
  - git
  - maven
  - nvm
  - vim
  - zsh

# homebrew cask applications
cask_applications:
  - android-studio
  - dbeaver-community
  - docker
  - franz
  - gitkraken
  - google-chrome
  - intellij-idea-ce
  - iterm2
  - java8
  - ngrok
  - spotify
  - visual-studio-code
  - vlc
  - zoomus

# manual download applications
downloads:
  fortclient:
    name: Fortclient 6.0.1
    url: https://filestore.fortinet.com/forticlient/downloads/FortiClientOnlineInstaller_6.0.1.dmg
    dest: "{{general.local_home}}/Downloads/FortiClientOnlineInstaller_6.0.1.dmg"
  tomcat:
    name: Tomcat 8.5.34
    url: http://ftp.unicamp.br/pub/apache/tomcat/tomcat-8/v8.5.34/bin/apache-tomcat-8.5.34.zip
    dest: "{{general.local_home}}/Downloads/apache-tomcat-8.5.34.zip"