---
# list of applications to install
general:
  local_home: "{{ lookup('env','HOME') }}"

# homebrew applications
applications:
  - docker
  - docker-compose
  - dotnet
  - git
  - nvm
  - openconnect
  - p7zip
  - ssh-copy-id
  - vim
  - yarn
  - zsh

# homebrew cask applications
cask_applications:
  - anki
  - dbeaver-community
  - franz
  - gitkraken
  - google-chrome
  - intellij-idea-ce
  - iterm2
  - libreoffice
  - ngrok
  - postman
  - spotify
  - slack
  - sourcetree
  - visual-studio-code
  - vlc
  - zoom

# manual download applications
downloads:
  tomcat:
    name: Tomcat 8.5.69
    url: https://downloads.apache.org/tomcat/tomcat-8/v8.5.69/bin/apache-tomcat-8.5.69.zip
    dest: "{{general.local_home}}/Downloads/apache-tomcat-8.5.34.zip"

#sdkman
sdkman_script_install_url: http://get.sdkman.io
sdkman_folder: '{{general.local_home}}/.sdkman'
gradle_version: 3.5
java_version: 11.0.11.hs-adpt
maven_version: 3.5.0