- name: ensure homebrew is updated 
  homebrew:
    state: latest
    update_homebrew: yes

- name: tap homebrew caskroom/cask
  homebrew_tap:
    tap: "caskroom/cask"

- name: tap homebrew caskroom/versions
  homebrew_tap:
    tap: "caskroom/versions"
