# - name: download applications
#   include: download.yml

- name: homebrew applications installs
  include: sdkman.yml

- name: homebrew applications installs
  include: homebrew.yml

- name: oh-my-zsh configurations
  include: oh-my-zsh.yml